basic_auth_server:
  container_name: "basic_auth_server"
  env_file: .env
  build: .
  volumes:
    - ".:/src"
  links:
    - "basic_auth_redis"
    - "basic_auth_mongo"
  ports:
    - "3000:3000"

basic_auth_redis:
  container_name: "basic_auth_redis"
  image: redis:3.2.1
  restart: always
  command: redis-server --appendonly yes
  volumes:
    - ./data:/data
  expose:
    - "6379"

basic_auth_mongo:
  container_name: "basic_auth_mongo"
  image: mongo:3.6
  restart: always
  volumes:
    - ./data:/data
  expose:
    - "27017"